baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Mega Gopher Project"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Alex Lanbin"
	description = "Super puper Gopher store"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "bygopher"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Программируй на Go<br/>вместе с новым другом"
		subtitle   = "Выпускаем Гоферов - культовый талисман Go сообщества"
		buttonText = "Подробнее"


	# About section
	[params.about]
		headline    = "У нас есть то, что вам нужно!"
		description = "Разработанный [Renee French](http://reneefrench.blogspot.ru/) символ языка программирования Go, идеальный подарок для любого поклонника данного языка, а также всех любителей милых плюшевых игрушек."
		buttonText  = "Текст на кнопке"


	# Service section
	[params.services]
		headline = "При заказе у нас"

    [[params.services.list]]
    	icon = "fa-diamond"
      title = "Оригинальный дизайн"
      description = "Our templates are updated regularly so they don't break."

    [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Гофер на ваш вкус"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
      icon = "fa-paper-plane"
      title = "Бесплатная доставка"
      description = "We update dependencies to keep things fresh."

    [[params.services.list]]
    	icon = "fa-heart"
      title = "Сделано с любовью"
      description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
